---
name: Quality Assurance
on:
  push:
    branches: ['main']
  pull_request: ~

jobs:
  tests:
    name: Tests on ${{ matrix.php }} ${{ matrix.composer-flags }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php: ['8.5']
        composer-flags: ['']
    steps:
      - name: Check out code
        uses: actions/checkout@v6
      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          coverage: xdebug
          extensions: gd, imagick
          tools: composer:v2
      - name: Install system dependencies
        run: sudo apt-get update && sudo apt-get install -y ghostscript
      - name: Install dependencies
        run: composer install --no-progress ${{ matrix.composer-flags }}
      - name: Run tests with coverage
        run: composer test:unit

  phpstan:
    name: PHPStan on ${{ matrix.php }} ${{ matrix.composer-flags }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php: ['8.5']
        composer-flags: ['']
    steps:
      - name: Check out code
        uses: actions/checkout@v6
      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          tools: composer:v2
      - name: Install dependencies
        run: composer install --no-progress ${{ matrix.composer-flags }}
      - name: Run static analysis
        run: vendor/bin/phpstan

  ecs:
    name: Code Style on ${{ matrix.php }} ${{ matrix.composer-flags }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php: ['8.5']
        composer-flags: ['']
    steps:
      - name: Check out code
        uses: actions/checkout@v6
      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          tools: composer:v2
      - name: Install dependencies
        run: composer install --no-progress ${{ matrix.composer-flags }}
      - name: Check code style
        run: vendor/bin/ecs check

  rector:
    name: Rector on ${{ matrix.php }} ${{ matrix.composer-flags }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php: ['8.5']
        composer-flags: ['']
    steps:
      - name: Check out code
        uses: actions/checkout@v6
      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          tools: composer:v2
      - name: Install dependencies
        run: composer install --no-progress ${{ matrix.composer-flags }}
      - name: Run Rector checks
        run: vendor/bin/rector --dry-run
